version: "3.4"

services:
  postfix:
    container_name: postfix
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_MAIL: ${SMTP_MAIL}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_SUBJECT: ${MAIL_SUBJECT}
      MAIL_RECIPIENT: ${MAIL_RECIPIENT}
    restart: on-failure
